service_accounts:
  publishing:
    name: publishing-sa@api-for-warp-drive.iam.gserviceaccount.com
    roles:
      - roles/aiplatform.user
      - roles/storage.admin
      - roles/secretmanager.secretAccessor

  deployment:
    name: deployment-sa@api-for-warp-drive.iam.gserviceaccount.com
    roles:
      - roles/container.developer
      - roles/storage.objectViewer
      - roles/cloudbuild.builds.builder

workload_identity:
  pool: projects/api-for-warp-drive/locations/global/workloadIdentityPools/github-pool
  provider: projects/api-for-warp-drive/locations/global/workloadIdentityPools/github-pool/providers/github